encyclopedia/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.homepage, name="homepage"), 
    path("wiki/", views.index, name="index"),
    path("wiki/<str:title>/", views.get_wiki, name="wiki"),
    path("search", views.wiki_search, name="wiki_search"),
    path("new/", views.add_wiki, name="add_wiki"),
    path("edit/<str:title>/", views.edit_wiki, name="edit_wiki"),
    path("delete/<str:title>/", views.delete_wiki, name="delete_wiki"),
    path("random/", views.random_wiki, name="random_wiki")
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wiki/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django import forms
from django.shortcuts import render, redirect
from django.contrib import messages
import random

from . import util

class NewSearchForm(forms.Form):
    query = forms.CharField(label=False, widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Search Encyclopedia", "autocomplete":"off"}))

class NewWikiForm(forms.Form):
    wiki_title = forms.CharField(label=False, widget=forms.TextInput(attrs={"class":"form-control","placeholder": "Wiki Title", "autocomplete": "off"}))
    wiki_content = forms.CharField(label=False, initial=util.default_textarea, widget=forms.Textarea(attrs={"class":"form-control"}))

def homepage(request):
    search_form = NewSearchForm()
    return render(request, "encyclopedia/homepage.html", {
        "homepage_title": "Encyclopedia - HomePage",
        "search_form": search_form
    })
    

def index(request):
    search_form = NewSearchForm()
    return render(request, "encyclopedia/index.html", {
        "title": "All Wiki Pages",
        "search_form": search_form,
        "entries": util.list_entries()
    })


def get_wiki(request, title):
    search_form = NewSearchForm()
    try:    
        html = util.markdown_to_html_converter(title)
        return render(request, "encyclopedia/wiki.html", {
            "search_form": search_form,
            "wiki_title": title,
            "wiki_content": html
        })
    except:
        return render(request, "encyclopedia/error.html", {
            "search_form": search_form,
            "wiki_title": title
        })
    

def wiki_search(request):
    # if request.method == "GET":
    search_form = NewSearchForm(request.GET)

    full_list = util.list_entries()
    full_list_lowercase = [item.lower() for item in full_list]

    if search_form.is_valid():
        query = search_form.cleaned_data["query"]
        sub_list = [ query_match for query_match in full_list if query.lower() in query_match.lower() ]

        if query.lower() in full_list_lowercase:
            # If query is found redirect to query wiki page
            return redirect(f"/wiki/{query}")
        elif len(sub_list) == 0:
            # if there is no matching elements in sub_list return error page
            return get_wiki(request, query)
        else:
            # If query not found then render matching elements list
            search_form = NewSearchForm()
            return render(request, "encyclopedia/index.html", {
                "title": "All Matching Wiki Pages",
                "search_form": search_form,
                "entries": sub_list
            })
    else:
        return index(request)


def add_wiki(request):
    search_form = NewSearchForm()
    add_form = NewWikiForm()

    full_list = util.list_entries()
    full_list_lowercase = [item.lower() for item in full_list]

    if request.method == "POST":
        add_form=NewWikiForm(request.POST)
        if add_form.is_valid():
            wiki_title = add_form.cleaned_data["wiki_title"]
            wiki_content= add_form.cleaned_data["wiki_content"]
            
            if wiki_title.lower() in full_list_lowercase:
                # If wiki already exist, prompt alert
                messages.error(request,"Sorry, this Wiki already exist!")

            else:
                # If wiki does not exist yet, redirect to new wiki page
                util.save_entry(wiki_title, wiki_content)
                messages.success(request, f"Your {wiki_title} Wiki page has been created!")
                return redirect(f"/wiki/{wiki_title}")        

    return render(request, "encyclopedia/add.html", {
        "title": "Add New Wiki",
        "search_form": search_form,
        "add_form": add_form
    })

def edit_wiki(request, title):
    search_form=NewSearchForm()
    edit_form=NewWikiForm(initial={"wiki_content": util.get_entry(title), "wiki_title": title})

    full_list = util.list_entries()
    full_list_lowercase = [item.lower() for item in full_list]

    if request.method == "POST":
        edit_form=NewWikiForm(request.POST)
        if edit_form.is_valid():
            edited_wiki_title = edit_form.cleaned_data["wiki_title"]
            edited_wiki_content = edit_form.cleaned_data["wiki_content"]
            util.save_entry(edited_wiki_title, edited_wiki_content)

            if edited_wiki_title.lower() in full_list_lowercase:
                messages.success(request, f"{edited_wiki_title} page has been updated!")            
            else: 
                messages.success(request, f"{edited_wiki_title} page has been created!")

        return redirect(f"/wiki/{edited_wiki_title}")  
    
    return render(request, "encyclopedia/edit.html", {
        "wiki_title": f"Edit Wiki {title}",
        "search_form": search_form,
        "edit_form": edit_form
    })

def delete_wiki(request, title):
    util.delete_entry(title)
    messages.error(request, f"{title} page has been deleted!")
    return redirect(f"/wiki")


def random_wiki(request):
    random_page =  random.choice(util.list_entries())
    return redirect(f"/wiki/{random_page}")
    
            

encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
<div class="messages">
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
</div>

<h1>{{ title }}</h1>

<div>
    <form action="{% url 'encyclopedia:add_wiki' %}" method="POST" class="add-form">
        {% csrf_token %}
        {{ add_form }}
        <input type="submit" value="Add New Wiki" class="btn btn-dark">
    </form>
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
<div class="messages">
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
</div>

<h1>{{ title }}</h1>

<div>
    <form action="{% url 'encyclopedia:create' %}" method="POST">
        {% csrf_token %}
        {{ create_form }}
        <input type="submit" value="Create New Wiki">
    </form>
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ wiki_title }}
{% endblock %}

{% block body %}
<div class="messages">
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
</div>

<h1>{{ wiki_title }}</h1>

<div>
    <form action="{% url 'encyclopedia:edit_wiki' wiki_title %}" method="POST" class="add-form">
        {% csrf_token %}
        {{ edit_form }}
        <input type="submit" value="{{ wiki_title }}" class="btn btn-dark">
    </form>
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Error
{% endblock %}

{% block body %}

<div>
    <h1>Page not found</h1>
    <h6>/404</h6>
    <p>The requested page <span><i>"{{ wiki_title }}"</i></span> was not found.</p>
    <p>Would you like to create <a href="{% url 'encyclopedia:add_wiki' %}">{{ wiki_title }}</a> ?</p>
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/homepage.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <title>{{ homepage_title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</head>

<body class="flex">
    <div class="flex homepage">
        <img src="{% static 'encyclopedia/images/wiki-logo.png' %}" alt="wiki-logo" class="homepage-img">
        <form action="{% url 'encyclopedia:wiki_search' %}" method="GET" class="flex homepage-form">
            {{ search_form }}
            <input type="submit" value="Wiki Search" class="btn btn-lg btn-dark">
        </form>
    </div>

</body>

</html>

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}

<div>
    <div class="messages">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    </div>

    <h1>{{ title }}</h1>

    <ul>
        {% for entry in entries %}
        <li><a href="{% url 'encyclopedia:wiki' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</head>

<body>
    <div class="sidebar flex">

        <div class="panel flex">
            <a href="{% url 'encyclopedia:homepage' %}">
                <img src="{% static 'encyclopedia/images/wiki-logo.png' %}" alt="wiki-logo" class="sidebar-img">
            </a>
            <h2>Wiki</h2>
            <form action="{% url 'encyclopedia:wiki_search' %}" method="GET" class="sidebar-form" style="width: 100%">
                {{ search_form }}
                <input type="submit" value="Wiki Search" class="btn btn-dark">
            </form>
            <div class="links flex">
                <div class="link">
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div class="link">
                    <a href="{% url 'encyclopedia:add_wiki' %}">Create New Wiki Page</a>
                </div>
                <div class="link">
                    <a href="{% url 'encyclopedia:random_wiki' %}">Random Wiki Page</a>
                </div>
            </div>

        </div>

        <div class="flex footer">
            <p><a href="https://cs50.harvard.edu/web/2020/projects/1/wiki/" target="_blank">Project 1 - Wiki</a></p>
            <p><a href="https://www.youtube.com/watch?v=Nn7EX3zkGUo&list=PLhQjrBD2T380xvFSUmToMMzERZ3qB5Ueu"
                    target="_blank">CS50’s Web Programming with Python and JavaScript</a></p>
            <p>Created by <a href="https://github.com/odakris?tab=repositories" target="_blank">odakris</a></p>
        </div>
        <!-- {% block nav %}
            {% endblock %} -->

    </div>
    <div class="main">
        {% block body %}
        {% endblock %}
    </div>
    <div class="flex footer media-query-footer">
        <p><a href="https://cs50.harvard.edu/web/2020/projects/1/wiki/" target="_blank">Project 1 - Wiki</a></p>
        <p><a href="https://www.youtube.com/watch?v=Nn7EX3zkGUo&list=PLhQjrBD2T380xvFSUmToMMzERZ3qB5Ueu"
                target="_blank">CS50’s Web Programming with Python and JavaScript</a></p>
        <p>Created by <a href="https://github.com/odakris?tab=repositories" target="_blank">odakris</a></p>
    </div>

</body>

</html>

encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}

<div class="messages">
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
</div>

<div class="buttons d-flex justify-content-between">
    <button type="button" class="btn btn-outline-primary"><strong>Edit Wiki</strong></button>
    <button type="button" class="btn btn-outline-danger"><strong>Delete</strong></button>
</div>

<hr>

<div>
    {{ page | safe }}
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ wiki_title }}
{% endblock %}

{% block body %}

<div class="messages">
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
</div>

<div class="buttons d-flex justify-content-between">
    <a href="{% url 'encyclopedia:edit_wiki' wiki_title %}"><button type="button"
            class="btn btn-outline-primary"><strong>Edit
                Wiki</strong></button></a>
    <a href="{% url 'encyclopedia:delete_wiki' wiki_title %}"><button type="button"
            class="btn btn-outline-danger"><strong>Delete</strong></button></a>
</div>

<hr>

<div>
    {{ wiki_content | safe }}
</div>

{% endblock %}